name: isnoda
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - bumpversion
  - cfgrib
  - coloredlogs
  - cython
  - dateparser=0.7.2
  - jinja2
  - make
  - matplotlib
  - mock
  - nco
  - netCDF4
  - numpy
  - pandas
  - pip
  - progressbar2
  - pykrige
  - python
  - pytz
  - pyyaml
  - regex
  - requests
  - setuptools_scm<4.2
  - scipy
  - siphon
  - sphinxcontrib-bibtex
  - sphinxcontrib-websupport
  - urllib3
  - utm
  - xarray
  - pip:
    - sphinx_rtd_theme
