name: isnobal
channels:
  - conda-forge
  - defaults
dependencies:
  - bumpversion 
  - beautifulsoup4
  - cfgrib 
  - coloredlogs 
  - cmocean
  - cython 
  - dateparser
  - jinja2
  - latexcodec
  - matplotlib 
  - mock 
  - make
  - nco
  - netCDF4 
  - numpy
  - pandas 
  - pip
  - pyproj=1.9 
  - python
  - pytz 
  - pyyaml 
  - regex
  - requests 
  - scipy
  - seaborn 
  - siphon 
  - sphinxcontrib-bibtex 
  - sphinxcontrib-websupport 
  - sqlalchemy
  - tox
  - utm
  - urllib3
  - watchdog
  - xarray 
  - pip:
    - "--no-deps https://github.com/USDA-ARS-NWRC/inicheck/archive/v0.7.8.tar.gz"
    - "--no-deps https://github.com/USDA-ARS-NWRC/PyKrige/archive/v1.4.0.tar.gz"
    - "--no-deps https://github.com/USDA-ARS-NWRC/snowav/archive/v0.11.6.tar.gz"
    - "--no-deps https://github.com/USDA-ARS-NWRC/spatialnc/archive/v0.2.12.tar.gz"
    - "--no-deps https://github.com/USDA-ARS-NWRC/tablizer/archive/v0.2.1.tar.gz"
    - mysql-connector-python-rf
    - sphinx_rtd_theme
